# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 12:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrt_desc', models.CharField(max_length=100, verbose_name='nom court')),
                ('long_desc', models.CharField(blank=True, default='', max_length=200, verbose_name='nom long')),
                ('ctdit_no', models.CharField(blank=True, max_length=10, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('maxqty', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='qte max pour 2000kcal/j')),
                ('pict', models.CharField(blank=True, max_length=300, null=True)),
                ('brand', models.NullBooleanField()),
                ('israw', models.NullBooleanField()),
                ('packpict', models.CharField(blank=True, max_length=300, null=True)),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Aliment et produit du commerce',
                'ordering': ['shrt_desc'],
            },
        ),
        migrations.CreateModel(
            name='NutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Aliment')),
            ],
            options={
                'ordering': ['nutriment'],
            },
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('nutr_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ifda_no', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('tagname', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nutr_no'],
            },
        ),
        migrations.CreateModel(
            name='PortionAliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pict', models.CharField(blank=True, max_length=300, null=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Aliment')),
            ],
            options={
                'ordering': ['aliment'],
            },
        ),
        migrations.AddField(
            model_name='nutdata',
            name='nutriment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Nutriment'),
        ),
    ]
