# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrt_desc', models.CharField(max_length=100)),
                ('long_desc', models.CharField(max_length=200)),
                ('ctdit_no', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('maxqty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pict', models.CharField(max_length=300)),
                ('brand', models.NullBooleanField()),
                ('israw', models.NullBooleanField()),
                ('packpict', models.CharField(max_length=300)),
                ('keywords', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['shrt_desc'],
                'db_table': 'aliment',
            },
        ),
        migrations.CreateModel(
            name='Nutdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('aliment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Aliment')),
            ],
            options={
                'db_table': 'nutdata',
            },
        ),
        migrations.CreateModel(
            name='Nutriment',
            fields=[
                ('nutr_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ifda_no', models.CharField(max_length=10)),
                ('unit', models.CharField(max_length=10)),
                ('tagname', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'nutriment',
            },
        ),
        migrations.CreateModel(
            name='Portionaliment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poids', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('pict', models.CharField(max_length=300)),
                ('aliment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Aliment')),
            ],
            options={
                'db_table': 'portionaliment',
            },
        ),
        migrations.AddField(
            model_name='nutdata',
            name='nutriment_id',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='aliments.Nutriment'),
        ),
    ]
