# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170212_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriuser',
            name='birthdate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='bmi',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='rda',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='weight',
            field=models.FloatField(blank=True),
        ),
    ]
