# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170212_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriuser',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
