# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 18:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('aliments', '0001_initial'),
        ('users', '0005_auto_20170212_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementRepas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbPortion', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('poids', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('aliment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Aliment')),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliments.Portionaliment')),
            ],
        ),
        migrations.CreateModel(
            name='Repas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2017, 2, 19, 18, 5, 1, 12022, tzinfo=utc))),
                ('no_repas', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nutriuser',
            name='rda',
            field=models.FloatField(default=2200),
        ),
        migrations.AddField(
            model_name='repas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elementrepas',
            name='repas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Repas'),
        ),
    ]
